server:
  port: 8081
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.30.100:3306/springcloud?characterEncoding=utf-8&useSSL=false&serverTimeZone=UTC

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7762/eureka/
      
mybatis:
  type-aliases-package: com.cloud.order.entity
  check-config-location: true
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapping/*.xml

env:
  dev

